# Replaces how i created a data source with the DataSourceFactory class
# into a more Spring Boot way.
spring.application.name=pdl-backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/media_items}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
